services:
  - type: web
    name: barcode-scanner-website
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /api/health
